project:
  type: website
  output-dir: docs

website:
  description: "A blog built with Quarto"
  site-url: "jay-uu.github.io/jayblog/" # you must change this appropriately for RSS feeds to work properly
  title: "jayblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      - minty
    css: styles.css
execute:
  freeze: auto


